name: TestEcosystem

on:
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag for manually running CI first code check workflow
        required: False
        default: ''

jobs:
  break:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dependent-packages: [
          "spec2vec",
        ]
#        pkgversion: [latest, stable]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependent packages
        run: |
          python -m pip install --upgrade pip poetry
          pip install ${{ matrix.dependent-packages }}
          pip install .
          pip check
        continue-on-error: true

      - name: Save compatibility result
        run: |
          set -v
          mkdir -p ./pr
          if pip check; then
            echo '{"package": "${{ matrix.dependent-packages }}", "version": 1.44, "numpy-version": 1.25, "run_success": true}' >> pr/result-${{ matrix.dependent-packages }}.json
            echo ".. image:: https://img.shields.io/badge/${{ matrix.dependent-packages }}-latest-green :alt: ${{ matrix.dependent-packages }} compatible" >> pr/${{ matrix.dependent-packages }}.rst
          else
            echo '{"package": "${{ matrix.dependent-packages }}", "version": 1.44, "numpy-version": 1.25, "run_success": false}' >> pr/result-${{ matrix.dependent-packages }}.json
            echo ".. image:: https://img.shields.io/badge/${{ matrix.dependent-packages }}-latest-red :alt: ${{ matrix.dependent-packages }} incompatible" >> pr/${{ matrix.dependent-packages }}.rst
          fi
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: badges
          path: pr/

  upload:
    needs: break
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: badges
          path: pr/

      - run: ls

      - name: List files
        run: |
          cd pr
          ls

      - name: Create results table
        run: |
          cd pr
            echo "| Package name | latest | stable |" > dependency-test-matrix.md
            echo "|--|--|--|" >> dependency-test-matrix.md
            count=0
            for file in *
            do
              [ "$file" == "NR" ] && continue
              [ "$file" == "dependency-test-matrix.md" ] && continue
              if [ $count == "0" ]; then
                name=$(echo $file | cut -f1 -d-)
                echo -n "| $name | "
              else
                echo -n "| "
              fi
              cat $file
              if [ $count == "0" ]; then
                echo -n " "
                count=1
              else
                echo " |"
                count=0
              fi
            done >> dependency-test-matrix.md

      - uses: actions/upload-artifact@v4
        with:
          name: dependency-test-matrix
          path: pr


#jobs:
#  test_ecosystem:
#    uses: ./.github/workflows/test_dependency.yml
#    strategy:
#      fail-fast: false
#      matrix:
#        numpy-version: [1.25, 2.1]
#        dependent-packages: ["ms2deepscore", "spec2vec"]
#    with:
#      numpy-version: ${{ matrix.numpy-version }}
#      dependent-packages: ${{ matrix.dependent-packages }}
#    secrets: inherit

#jobs:
#  test_ecosystem:
#    name: Test ecosystem / numpy-${{ matrix.numpy-version }} / ${{ matrix.dependent-packages }}
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        numpy-version: [1.25, 2.1]
#        dependent-packages: ["package1", "package2"]
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.11'
#
#      - name: Install dependent packages
#        run: |
#          python -m pip install --upgrade pip poetry
#          pip install numpy==${{ matrix.numpy-version }}
#          pip install ${{ matrix.dependent-packages }}
#          pip install .
#          pip check
#
#      - name: Generate Badge Status
#        run: |
#          mkdir -p badges
#          echo "{ \"schemaVersion\": 1, \"label\": \"numpy-${{ matrix.numpy-version }}\", \"message\": \"$([[ ${{ success() }} == 'true' ]] && echo success || echo failure)\", \"color\": \"$([[ ${{ success() }} == 'true' ]] && echo green || echo red)\" }" > badges/numpy-${{ matrix.numpy-version }}-${{ matrix.dependent-packages }}.json
#
#      - name: Upload Badge Artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: badge-numpy-${{ matrix.numpy-version }}-${{ matrix.dependent-packages }}
#          path: badges/numpy-${{ matrix.numpy-version }}-${{ matrix.dependent-packages }}.json
#
#
#
#
##jobs:
#  test_ecosystem:
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        numpy-version: [ 1.25, 2.1 ]
#        dependent-packages: [ 'ms2deepscore', 'ms2query', 'spec2vec' ]
#    steps:
#      - name: Trigger sub-jobs
#        run: |
#          echo "Creating separate jobs for each matrix combination"
#        id: trigger

#jobs:
#  test_ecosystem:
#    name: numpy-${{ matrix.numpy-version }}-${{ matrix.dependent-packages }}
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        numpy-version: [ 1.25, 2.1 ]
#        dependent-packages: [ 'ms2deepscore', 'ms2query', 'spec2vec' ]
#    outputs:
#      json-path: result.json
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.11'
#
#      - name: Install dependent packages
#        run: |
#          python -m pip install --upgrade pip poetry
#          pip install numpy==${{ matrix.numpy-version }}
#          pip install ${{ matrix.dependent-packages }}
#          pip install .
#          pip check
#
#      - name: Show pip list
#        run: |
#          pip list
#
#      - name: Create Badge URLs
#        run: |
#          echo "badge_url=https://github.com/julianpollmann/matchms/actions/workflows/test_ecosystem.yml/badge.svg?branch=${{ github.ref_name }}&numpy=${{ matrix.numpy-version }}&dependent-packages=${{ matrix.dependent-packages }}" >> $GITHUB_OUTPUT



#      - name: Generate job result
#        run: |
#          echo '{
#            "job_name": "generate-artifact",
#            "status": "${{ job.status }}",
#            "results": {
#              "numpy-version": "${{ matrix.numpy-version }}"
#            }
#          }' > result.json
#
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: job-result-${{ matrix.numpy-version }}
#          path: result.json

#      - name: Save status for Shields.io
#        run: |
#          echo "::set-output name=job_status::${{ job.status }}"
#          echo "::set-output name=numpy_version::${{ matrix.numpy-version }}"
#          echo "::set-output name=package::${{ matrix.dependent-packages }}"
#
#      - name: Generate Shields.io badge URL
#        run: |
#          BASE_URL="https://img.shields.io/badge"
#          LABEL="Matchms-numpy_${{ matrix.numpy-version }}-${{ matrix.dependent-packages }}"
#          STATUS="${{ steps.save-status.outputs.job_status }}"
#          COLOR="green"
#          if [[ "${STATUS}" == "failed" ]]; then
#            COLOR="red"
#          fi
#          BADGE_URL="${BASE_URL}/${LABEL}-${STATUS}-${COLOR}"
#          echo "Badge URL: ${BADGE_URL}"
