name: TestEcosystem

on:
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag for manually running CI first code check workflow
        required: False
        default: ''

jobs:
  test_dependencies:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dependent-packages: ["spec2vec"]
        numpy-version: [1.25, 2.1]
    outputs:
      numpy1: ${{ steps.set_numpy_version.outputs.numpy1 }}
      numpy2: ${{ steps.set_numpy_version.outputs.numpy2 }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependent packages
        run: |
          python -m pip install --upgrade pip poetry
          pip install numpy==${{ matrix.numpy-version }}
          pip install ${{ matrix.dependent-packages }}
          pip install .
          pip check
        continue-on-error: true

      - name: Set numpy version
        id: set_numpy_version
        run: |
          numpy_version="${{ matrix.numpy-version }}"
          if [[ $numpy_version == 2* ]]; then
              echo "numpy2=${numpy_version}" >> "$GITHUB_OUTPUT"
          else
              echo "numpy1=${numpy_version}" >> "$GITHUB_OUTPUT"
          fi

      - name: Save compatibility result
        run: |
          set -v
          mkdir -p ./pr

          version=$(pip show "${{ matrix.dependent-packages }}" | grep Version | awk '{print $2}')

          if pip check; then
            echo "{\"package\": \"${{ matrix.dependent-packages }}\", \"version\": \"$version\", \"numpy-version\": \"${{ matrix.numpy-version }}\", \"run_success\": true}" >> pr/${{ matrix.numpy-version }}-${{ matrix.dependent-packages }}.json
          else
            echo "{\"package\": \"${{ matrix.dependent-packages }}\", \"version\": \"$version\", \"numpy-version\": \"${{ matrix.numpy-version }}\", \"run_success\": false}" >> pr/${{ matrix.numpy-version }}-${{ matrix.dependent-packages }}.json
          fi
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: dependency-results-${{ matrix.numpy-version }}-${{ matrix.dependent-packages }}
          path: pr/





  combine_results:
    needs: test_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - env:
          OUTPUT1: ${{needs.test_dependencies.outputs.numpy1}}
          OUTPUT2: ${{needs.test_dependencies.outputs.numpy2}}
        run: |
          echo "NUMPY1=$OUTPUT1" >> $GITHUB_ENV
          echo "NUMPY2=$OUTPUT2" >> $GITHUB_ENV

      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: pr/

      - run: ls

      - name: List files
        run: |
          cd pr
          ls

      - name: Create results table
        run: |
          cd pr
          ls

          numpy_versions=("$NUMPY1" "$NUMPY2")

          output_file="dependency-matrix.md"
          echo "| NumPy Version | spec2vec Status | ms2query Status |" > output_file
          echo "|---------------|-----------------|-----------------|" >> output_file

          for numpy_version in "${numpy_versions[@]}"; do
            outstring="| ![Static Badge](https://img.shields.io/badge/numpy-${numpy_version}-lightgrey?logo=numpy) | "

            spec2vec_file="${numpy_version}-spec2vec.json"
            ms2query_file="${numpy_version}-spec2vec.json"

            if [[ -n "$spec2vec_file" ]]; then
              package=$(jq -r '.package' "$spec2vec_file")
              version=$(jq -r '.version' "$spec2vec_file")
              run_success=$(jq -r '.run_success' "$spec2vec_file")

              badge_color=$([[ "$run_success" == "true" ]] && echo "green" || echo "red")

              outstring="${outstring} ${badge_color} |"
            else
              outstring="${outstring} |"
            fi

            if [[ -n "$ms2query_file" ]]; then
              package=$(jq -r '.package' "$spec2vec_file")
              version=$(jq -r '.version' "$spec2vec_file")
              run_success=$(jq -r '.run_success' "$spec2vec_file")

              badge_color=$([[ "$run_success" == "true" ]] && echo "green" || echo "red")

              outstring="${outstring} ${badge_color} |"
            else
              outstring="${outstring} |"
            fi

            echo $outstring >> output_file
          done





#          # Start der Tabelle
#          cat <<EOF > "$output_file"
#          .. list-table::
#             :header-rows: 1
#
#             * - numpy
#               - spec2vec
#               - ms2query
#               - ms2deepscore
#          EOF
#
#          # Array für die numpy-Versionen, basierend auf den JSON-Dateien
#          numpy_versions=("${{ env.NUMPY1 }}" "${{ env.NUMPY2 }}")
#
#          # Finde alle JSON-Dateien im pr/ Ordner
#          json_files=$(ls *.json)
#
#          # Iteriere über alle JSON-Dateien
#          for json_file in $json_files; do
#            # Extrahiere numpy-version, package, version und run_success aus der JSON-Datei
#            numpy_version=$(jq -r '.["numpy-version"]' "$json_file")
#            package=$(jq -r '.package' "$json_file")
#            version=$(jq -r '.version' "$json_file")
#            run_success=$(jq -r '.run_success' "$json_file")
#
#            # Bestimme die Badge-Farbe je nach Erfolg des Runs
#            badge_color=$([[ "$run_success" == "true" ]] && echo "green" || echo "red")
#
#            # Zeile zur Tabelle hinzufügen
#            cat <<EOF >> "$output_file"
#             * - .. image:: https://img.shields.io/badge/numpy-${numpy_version}-green?logo=numpy :alt: numpy
#               - .. image:: https://img.shields.io/badge/${package}-${version}-${badge_color} :alt: ${package}
#               - .. image:: https://img.shields.io/badge/${package}-${version}-${badge_color} :alt: ${package}
#          EOF
#          done

      - uses: actions/upload-artifact@v4
        with:
          name: dependency-test-matrix
          path: pr





















#jobs:
#  test_ecosystem:
#    uses: ./.github/workflows/test_dependency.yml
#    strategy:
#      fail-fast: false
#      matrix:
#        numpy-version: [1.25, 2.1]
#        dependent-packages: ["ms2deepscore", "spec2vec"]
#    with:
#      numpy-version: ${{ matrix.numpy-version }}
#      dependent-packages: ${{ matrix.dependent-packages }}
#    secrets: inherit

#jobs:
#  test_ecosystem:
#    name: Test ecosystem / numpy-${{ matrix.numpy-version }} / ${{ matrix.dependent-packages }}
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        numpy-version: [1.25, 2.1]
#        dependent-packages: ["package1", "package2"]
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.11'
#
#      - name: Install dependent packages
#        run: |
#          python -m pip install --upgrade pip poetry
#          pip install numpy==${{ matrix.numpy-version }}
#          pip install ${{ matrix.dependent-packages }}
#          pip install .
#          pip check
#
#      - name: Generate Badge Status
#        run: |
#          mkdir -p badges
#          echo "{ \"schemaVersion\": 1, \"label\": \"numpy-${{ matrix.numpy-version }}\", \"message\": \"$([[ ${{ success() }} == 'true' ]] && echo success || echo failure)\", \"color\": \"$([[ ${{ success() }} == 'true' ]] && echo green || echo red)\" }" > badges/numpy-${{ matrix.numpy-version }}-${{ matrix.dependent-packages }}.json
#
#      - name: Upload Badge Artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: badge-numpy-${{ matrix.numpy-version }}-${{ matrix.dependent-packages }}
#          path: badges/numpy-${{ matrix.numpy-version }}-${{ matrix.dependent-packages }}.json
#
#
#
#
##jobs:
#  test_ecosystem:
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        numpy-version: [ 1.25, 2.1 ]
#        dependent-packages: [ 'ms2deepscore', 'ms2query', 'spec2vec' ]
#    steps:
#      - name: Trigger sub-jobs
#        run: |
#          echo "Creating separate jobs for each matrix combination"
#        id: trigger

#jobs:
#  test_ecosystem:
#    name: numpy-${{ matrix.numpy-version }}-${{ matrix.dependent-packages }}
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        numpy-version: [ 1.25, 2.1 ]
#        dependent-packages: [ 'ms2deepscore', 'ms2query', 'spec2vec' ]
#    outputs:
#      json-path: result.json
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.11'
#
#      - name: Install dependent packages
#        run: |
#          python -m pip install --upgrade pip poetry
#          pip install numpy==${{ matrix.numpy-version }}
#          pip install ${{ matrix.dependent-packages }}
#          pip install .
#          pip check
#
#      - name: Show pip list
#        run: |
#          pip list
#
#      - name: Create Badge URLs
#        run: |
#          echo "badge_url=https://github.com/julianpollmann/matchms/actions/workflows/test_ecosystem.yml/badge.svg?branch=${{ github.ref_name }}&numpy=${{ matrix.numpy-version }}&dependent-packages=${{ matrix.dependent-packages }}" >> $GITHUB_OUTPUT



#      - name: Generate job result
#        run: |
#          echo '{
#            "job_name": "generate-artifact",
#            "status": "${{ job.status }}",
#            "results": {
#              "numpy-version": "${{ matrix.numpy-version }}"
#            }
#          }' > result.json
#
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: job-result-${{ matrix.numpy-version }}
#          path: result.json

#      - name: Save status for Shields.io
#        run: |
#          echo "::set-output name=job_status::${{ job.status }}"
#          echo "::set-output name=numpy_version::${{ matrix.numpy-version }}"
#          echo "::set-output name=package::${{ matrix.dependent-packages }}"
#
#      - name: Generate Shields.io badge URL
#        run: |
#          BASE_URL="https://img.shields.io/badge"
#          LABEL="Matchms-numpy_${{ matrix.numpy-version }}-${{ matrix.dependent-packages }}"
#          STATUS="${{ steps.save-status.outputs.job_status }}"
#          COLOR="green"
#          if [[ "${STATUS}" == "failed" ]]; then
#            COLOR="red"
#          fi
#          BADGE_URL="${BASE_URL}/${LABEL}-${STATUS}-${COLOR}"
#          echo "Badge URL: ${BADGE_URL}"
