name: Test dependency

on:
  workflow_call:
    inputs:
      numpy-version:
        required: true
        type: number
      dependent-packages:
        required: true
        type: string

jobs:
  test_dependency:
    name: numpy-${{ inputs.numpy-version }} / ${{ inputs.dependent-packages }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependent packages
        run: |
          python -m pip install --upgrade pip poetry
          pip install numpy==${{ inputs.numpy-version }}
          pip install ${{ inputs.dependent-packages }}
          pip install .
          pip check
